//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hit.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hit.Services.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Delete from DB because there is a related record in table {0}.
        /// </summary>
        public static string DELETEFOREIGNKEYCONSTRAINT {
            get {
                return ResourceManager.GetString("DELETEFOREIGNKEYCONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0} must be greater than 0.
        /// </summary>
        public static string GREATERTHANZERO {
            get {
                return ResourceManager.GetString("GREATERTHANZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0} must be greater than 0 or equal to 0.
        /// </summary>
        public static string GREATERTHANZEROORZERO {
            get {
                return ResourceManager.GetString("GREATERTHANZEROORZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Insert to DB because there is no related record in table {0}.
        /// </summary>
        public static string INSERTFOREIGNKEYCONSTRAINT {
            get {
                return ResourceManager.GetString("INSERTFOREIGNKEYCONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Arguments.
        /// </summary>
        public static string InvalidArguments {
            get {
                return ResourceManager.GetString("InvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List must have at least one element.
        /// </summary>
        public static string LISTONEELEMENT {
            get {
                return ResourceManager.GetString("LISTONEELEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation is not checked in..
        /// </summary>
        public static string NOTCHECKEDIN {
            get {
                return ResourceManager.GetString("NOTCHECKEDIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0}  field is required..
        /// </summary>
        public static string PROPERTYISREQUIRED {
            get {
                return ResourceManager.GetString("PROPERTYISREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation not found.
        /// </summary>
        public static string RESERVATIONNOTFOUND {
            get {
                return ResourceManager.GetString("RESERVATIONNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room not found.
        /// </summary>
        public static string ROOMNOTFOUND {
            get {
                return ResourceManager.GetString("ROOMNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Base Error..
        /// </summary>
        public static string SQLERROR {
            get {
                return ResourceManager.GetString("SQLERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code already exists into DB.
        /// </summary>
        public static string SQLVIOLATIONOFUNIQUEKEY {
            get {
                return ResourceManager.GetString("SQLVIOLATIONOFUNIQUEKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one To email address is required.
        /// </summary>
        public static string TOEMAILISREQUIRED {
            get {
                return ResourceManager.GetString("TOEMAILISREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User..
        /// </summary>
        public static string UNAUTHORIZEDUSER {
            get {
                return ResourceManager.GetString("UNAUTHORIZEDUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Update to DB because there is no related record in table {0}.
        /// </summary>
        public static string UPDATEFOREIGNKEYCONSTRAINT {
            get {
                return ResourceManager.GetString("UPDATEFOREIGNKEYCONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error authenticating user.
        /// </summary>
        public static string USERAUTHENTICATION {
            get {
                return ResourceManager.GetString("USERAUTHENTICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Errors.
        /// </summary>
        public static string VALIDATIONERRORS {
            get {
                return ResourceManager.GetString("VALIDATIONERRORS", resourceCulture);
            }
        }
    }
}
