using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Hit.Services.DTOs.Protel
{
    [Table("ukto")]
    public class UktoDTO
    {
        public int mpehotel { get; set; } //(int, not null)
        public string kto { get; set; } //(varchar(10), not null)
        public string bez { get; set; } //(varchar(40), not null)
        public string posttext { get; set; } //(varchar(40), not null)
        public int ktonr { get; set; } //(int, not null)
        public int hauptgrp { get; set; } //(int, not null)
        public int mwstnr { get; set; } //(int, not null)
        public decimal tax1 { get; set; } //(decimal(10,6), not null)
        public decimal tax2 { get; set; } //(decimal(10,6), not null)
        public decimal tax3 { get; set; } //(decimal(10,6), not null)
        public decimal extax { get; set; } //(decimal(10,6), not null)
        public decimal extaxanz { get; set; } //(decimal(19,2), not null)
        public int extaxmode { get; set; } //(int, not null)
        public int extaxmode2 { get; set; } //(int, not null)
        public int extaxukto { get; set; } //(int, not null)
        public string extaxtext { get; set; } //(varchar(20), not null)
        public decimal extax2 { get; set; } //(decimal(10,6), not null)
        public decimal extax2anz { get; set; } //(decimal(19,2), not null)
        public int extaxukto2 { get; set; } //(int, not null)
        public string extaxtext2 { get; set; } //(varchar(20), not null)
        public decimal extax3 { get; set; } //(decimal(10,6), not null)
        public decimal extax3anz { get; set; } //(decimal(19,2), not null)
        public int extaxukto3 { get; set; } //(int, not null)
        public string extaxtext3 { get; set; } //(varchar(20), not null)
        public decimal extax4 { get; set; } //(decimal(10,6), not null)
        public decimal extax4anz { get; set; } //(decimal(19,2), not null)
        public int extaxukto4 { get; set; } //(int, not null)
        public string extaxtext4 { get; set; } //(varchar(20), not null)
        public decimal extax5 { get; set; } //(decimal(10,6), not null)
        public decimal extax5anz { get; set; } //(decimal(19,2), not null)
        public int extaxukto5 { get; set; } //(int, not null)
        public string extaxtext5 { get; set; } //(varchar(20), not null)
        public decimal extax6 { get; set; } //(decimal(10,6), not null)
        public decimal extax6anz { get; set; } //(decimal(19,2), not null)
        public int extaxukto6 { get; set; } //(int, not null)
        public string extaxtext6 { get; set; } //(varchar(20), not null)
        public decimal extax7 { get; set; } //(decimal(10,6), not null)
        public decimal extax7anz { get; set; } //(decimal(19,2), not null)
        public int extaxukto7 { get; set; } //(int, not null)
        public string extaxtext7 { get; set; } //(varchar(20), not null)
        public int extaxsub { get; set; } //(int, not null)
        public int extaxsub2 { get; set; } //(int, not null)
        public int extaxsub3 { get; set; } //(int, not null)
        public int extaxsub4 { get; set; } //(int, not null)
        public int extaxsub5 { get; set; } //(int, not null)
        public int extaxsub6 { get; set; } //(int, not null)
        public int extaxsub7 { get; set; } //(int, not null)
        public int curr { get; set; } //(int, not null)
        public decimal epreis { get; set; } //(decimal(19,2), not null)
        public int statgrp { get; set; } //(int, not null)
        public int autoroute { get; set; } //(int, not null)
        public string gvkonto { get; set; } //(varchar(20), not null)
        public string kst1 { get; set; } //(varchar(20), not null)
        public string kst2 { get; set; } //(varchar(20), not null)
        public int datevkto { get; set; } //(int, not null)
        public int kasbuch { get; set; } //(int, not null)
        public int kaspay { get; set; } //(int, not null)
        public int ispack { get; set; } //(int, not null)
        public int fixmode { get; set; } //(int, not null)
        public int taxgrpmode { get; set; } //(int, not null)
        public int ifckonto { get; set; } //(int, not null)
        public int ifckonto_hide_in_sd { get; set; } //(int, not null)
        public int vcode { get; set; } //(int, not null)
        public int redvat { get; set; } //(int, not null)
        public int poq { get; set; } //(int, not null)
        public int redvatdays { get; set; } //(int, not null)
        public string ord1 { get; set; } //(varchar(25), not null)
        public string ord2 { get; set; } //(varchar(25), not null)
        public string ord3 { get; set; } //(varchar(25), not null)
        public string ord4 { get; set; } //(varchar(25), not null)
        public int inet { get; set; } //(int, not null)
        public decimal ums_tag { get; set; } //(decimal(19,2), not null)
        public decimal ums_monat { get; set; } //(decimal(19,2), not null)
        public decimal ums_jahr { get; set; } //(decimal(19,2), not null)
    }

}
