//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hit.Services.DataAccess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HpkWzJOvE+nTPeXiEK5WD24WLAqsUb8LziXzwbDLRfWcV8bnPKJH8k6Fxusy4dIG6IdGcL+UdZvXHzirO" +
            "EH21CX8x9M19F9+cm8nx3MdrnPvt2NvW64JwlRJnmxtt7l2vFqI4cCXKMoIEzLIwmx8VASd/16ma46ff" +
            "/NtLe2j6nHJ1cQx2+ba4aD1yE/UD0zKnbSjb0Li/0fJHjMuChMiUSU2IxC++4ewqZP+AzxvV2Y=")]
        public string ProtelDB {
            get {
                return ((string)(this["ProtelDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HpkWzJOvE+nTPeXiEK5WD24WLAqsUb8LziXzwbDLRfWcV8bnPKJH8k6Fxusy4dIG6IdGcL+UdZvXHzirO" +
            "EH21DsmEo4lPiJqejBlUSK4JMhpH+x+L+DkgJADb3KPXYGSaFHlOmqO4jMoTE0I8870D84vGzN6pr8Qy" +
            "IKoub3V8H+spuvv71slzfQMLdQ0R8FmCGMbbnNW2V4OsZVtoQjlVg==")]
        public string SmartInElockDB {
            get {
                return ((string)(this["SmartInElockDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("proteluser")]
        public string ProtelUser {
            get {
                return ((string)(this["ProtelUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string Mpehotel {
            get {
                return ((string)(this["Mpehotel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-")]
        public string HitPosDB {
            get {
                return ((string)(this["HitPosDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"HdgOyzBOEmhCugwCpm31D8P5wp7pbN02oLn+NZTWL5BxF6e01ikUy2+88+ID3PtTQcXkLNz+59VusMOioS42kcDqivlVCBt2xhi85DRRejy0Rsx4MpDBmx1iESm1PgV1+O6TZhRzuCaQChLGOlHOUkEmz3PeW8FkkquAgUZ4cGNM++r7f5WXuc2V4X+idM0DHKIFUiSP75Uom/q7BAK2GtgDTTnTjywlPQGtRYbltTHOG8uaFzNORqnFM5zuE51o4+lw2ISAo+FN+4hjZuGC6TJiigLjZ0sWPIByH92v4eg=")]
        public string WebPosDB {
            get {
                return ((string)(this["WebPosDB"]));
            }
        }
    }
}
